project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel Shpigel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - posts.qmd
      - howtos.qmd

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true
    code-tools:
      source: true
      toggle: false
      caption: none